FROM python:3.10.12
WORKDIR /app
COPY /Facial_Recognize/requirements.txt .
RUN apt-get update && \
    apt-get install -y python3-opencv && \
    pip install -r requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY Facial_Recognize .
CMD ["python", "Facial_Recognize/api.py"]
EXPOSE 5000